import LeaveAllowance from 'components/admin timeoffs/components/LeaveAllowance';

export default {
    dashboard: '/dashboard',
    overview: '/overview',
    carrer: '/carrer',
    // unauthorized: '/unAuthorized',
    notAuthorized: '/unAuthorized',
    overviewTwo: '/overview/two',
    myprofile: '/myprofile',
    employementform: '/employmentform',

    employees: '/employees',
    timeoff: '/timeoff',
    projects: '/projects',
    holidays: '/holidays',
    timeoffs: '/Timeoffs',
    attendance: '/attendance',
    admineducations: '/admineducations',
    adminattendance: '/adminattendance',
    adminskills: '/adminskills',
    LeaveAllowance: '/LeaveAllowance',

    agents: '/agents',
    articles: '/articles',
    designations: '/designations',
    admintimeoffs: '/admintimeoffs',
    departments: '/departments',
    educations: '/educations',
    importerror: '/importError',
    skills: '/skills',
    assets: '/assets',
    empholidays: '/empholidays',
    emptimeoffs: '/timeoffs',
    invoice: '/invoice',
    learning: '/learning',
    empLeaves: '/empLeaves',
    employeeView: (userId) => `/employee/${userId}`,
    employeeAdd: '/public/employee-add',
    signin: '/signin',
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgotpassword',
    resetpassword: '/resetPassword',
    emailrequest: '/emailrequest',
    forgotpasswordform: '/forgotpasswordform'
};
